Development weblets docs
threefoldtech/info_grid pull request #226
Opened 2023-08-02 12:08 UTC by maayarosama

### Description

Renaming files in playground docs
re-adding sections in weblets docs

### Related Issues
#217
#120

2023-08-02 12:18 UTC, AhmedHanafy725 commented on src/playground/wallet_connector.md
> +# Profile Manager
can we rename it inside the file to wallet connector too?

2023-08-02 15:01 UTC, AhmedHanafy725 requested changes

2023-08-02 15:03 UTC, AhmedHanafy725 commented on src/playground/k8s.md
> +- Make sure you have an activated [profile](./wallet_connector.md)
this should be applied to all files

2023-08-02 15:50 UTC, AhmedHanafy725 commented on src/playground/caprover.md
> +- [Make sure your profile is activated](./wallet_connector.md)
```suggestion
- [Make sure your wallet is connected](./wallet_connector.md)
```

2023-08-02 22:08 UTC, Mik-TF commented
I adjusted some inner TOC links, like sys admins TOC and others.

2023-08-02 22:08 UTC, Mik-TF approved these changes

2023-08-02 22:21 UTC, Mik-TF commented
@AhmedHanafy725 
It seems that SSH wasn't in the summary.md.

I added it in summary.md, and the toc for playground and sys admin.

Let me know if you want to put it elsewhere.
<img width="294" alt="ssh_menu" src="https://github.com/threefoldtech/info_grid/assets/77026219/7608e235-dc29-49cf-82cd-f4f3ee1046c9">

2023-08-02 22:23 UTC, Mik-TF commented
<img width="303" alt="Screen Shot 2023-08-02 at 6 22 45 PM" src="https://github.com/threefoldtech/info_grid/assets/77026219/0836802c-e5cf-4a67-958e-52e35fe9235c">

Maybe it would be better to have a SSH section in Getting Started, and have 

* SSH
   *  SSH Remote Connection
   * SSH on WSL

2023-08-03 04:16 UTC, Mik-TF commented
I re-organized the SSH section to present the 3 main methods, openssh, putty and wsl.

2023-08-03 04:37 UTC, Mik-TF approved these changes
All the changes should be there.

2023-08-03 07:15 UTC, AhmedHanafy725 approved these changes

2023-08-03 07:16 UTC, merged